package pe.nanamochi.banchus.packets;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Packets {

    // Client
    OSU_USER_STATUS(0),
    OSU_MESSAGE(1),
    OSU_EXIT(2),
    OSU_STATUS_UPDATE_REQUEST(3),
    OSU_PONG(4),
    OSU_START_SPECTATING(16),
    OSU_STOP_SPECTATING(17),
    OSU_SPECTATE_FRAMES(18),
    OSU_ERROR_REPORT(20),
    OSU_CANT_SPECTATE(21),
    OSU_PRIVATE_MESSAGE(25),
    OSU_LOBBY_PARTY(29),
    OSU_LOBBY_JOIN(30),
    OSU_MATCH_CREATE(31),
    OSU_MATCH_JOIN(32),
    OSU_MATCH_PARTY(33),
    OSU_MATCH_CHANGE_SLOT(38),
    OSU_MATCH_READY(39),
    OSU_MATCH_LOCK(40),
    OSU_MATCH_CHANGE_SETTINGS(41),
    OSU_MATCH_START(44),
    OSU_MATCH_SCORE_UPDATE(47),
    OSU_MATCH_COMPLETE(49),
    OSU_MATCH_CHANGE_MODS(51),
    OSU_MATCH_LOAD_COMPLETE(52),
    OSU_MATCH_NO_BEATMAP(54),
    OSU_MATCH_NOT_READY(55),
    OSU_MATCH_FAILED(56),
    OSU_MATCH_HAS_BEATMAP(59),
    OSU_MATCH_SKIP_REQUEST(60),
    OSU_CHANNEL_JOIN(63),
    OSU_BEATMAP_INFO_REQUEST(68),
    OSU_MATCH_TRANSFER_HOST(70),
    OSU_FRIENDS_ADD(73),
    OSU_FRIENDS_REMOVE(74),
    OSU_MATCH_CHANGE_TEAM(77),
    OSU_CHANNEL_LEAVE(78),
    OSU_RECEIVE_UPDATES(79),
    OSU_SET_IRC_AWAY_MESSAGE(82),
    OSU_USER_STATS_REQUEST(85),
    OSU_INVITE(87),
    OSU_MATCH_CHANGE_PASSWORD(90),
    OSU_TOURNAMENT_MATCH_INFO(93),
    OSU_PRESENCE_REQUEST(97),
    OSU_PRESENCE_REQUEST_ALL(98),
    OSU_CHANGE_FRIEND_ONLY_DMS(99),
    OSU_TOURNAMENT_JOIN_MATCH_CHANNEL(108),
    OSU_TOURNAMENT_LEAVE_MATCH_CHANNEL(109),

    // Server
    BANCHO_LOGIN_REPLY(5),
    BANCHO_COMMAND_ERROR(6),
    BANCHO_MESSAGE(7),
    BANCHO_PING(8),
    BANCHO_IRC_CHANGE_USERNAME(9),
    BANCHO_IRC_QUIT(10),
    BANCHO_USER_STATS(11),
    BANCHO_USER_QUIT(12),
    BANCHO_SPECTATOR_JOINED(13),
    BANCHO_SPECTATOR_LEFT(14),
    BANCHO_SPECTATE_FRAMES(15),
    BANCHO_VERSION_UPDATE(19),
    BANCHO_SPECTATOR_CANT_SPECTATE(22),
    BANCHO_GET_ATTENTION(23),
    BANCHO_ANNOUNCE(24),
    BANCHO_MATCH_UPDATE(26),
    BANCHO_MATCH_NEW(27),
    BANCHO_MATCH_DISBAND(28),
    BANCHO_LOBBY_JOIN(34),
    BANCHO_LOBBY_PART(35),
    BANCHO_MATCH_JOIN_SUCCESS(36),
    BANCHO_MATCH_JOIN_FAIL(37),
    BANCHO_FELLOW_SPECTATOR_JOINED(42),
    BANCHO_FELLOW_SPECTATOR_LEFT(43),
    BANCHO_MATCH_START(46),
    BANCHO_MATCH_SCORE_UPDATE(48),
    BANCHO_MATCH_TRANSFER_HOST(50),
    BANCHO_MATCH_ALL_PLAYERS_LOADED(53),
    BANCHO_MATCH_PLAYER_FAILED(57),
    BANCHO_MATCH_COMPLETE(58),
    BANCHO_MATCH_SKIP(61),
    BANCHO_UNAUTHORIZED(62),
    BANCHO_CHANNEL_JOIN_SUCCESS(64),
    BANCHO_CHANNEL_AVAILABLE(65),
    BANCHO_CHANNEL_REVOKED(66),
    BANCHO_CHANNEL_AVAILABLE_AUTOJOIN(67),
    BANCHO_BEATMAP_INFO_REPLY(69),
    BANCHO_LOGIN_PERMISSIONS(71),
    BANCHO_FRIENDS_LIST(72),
    BANCHO_PROTOCOL_NEOGITIATION(75),
    BANCHO_TITLE_UPDATE(76),
    BANCHO_MONITOR(80),
    BANCHO_MATCH_PLAYER_SKIPPED(81),
    BANCHO_USER_PRESENCE(83),
    BANCHO_RESTART(86),
    BANCHO_INVITE(88),
    BANCHO_CHANNEL_INFO_COMPLETE(89),
    BANCHO_MATCH_CHANGE_PASSWORD(91),
    BANCHO_SILENCE_INFO(92),
    BANCHO_USER_SILENCED(94),
    BANCHO_USER_PRESENCE_SINGLE(95),
    BANCHO_USER_PRESENCE_BUNDLE(96),
    BANCHO_USER_DMS_BLOCKED(100),
    BANCHO_TARGET_IS_SILENCED(101),
    BANCHO_VERSION_UPDATE_FORCED(102),
    BANCHO_SWITCH_SERVER(103),
    BANCHO_ACCOUNT_RESTRICTED(104),
    BANCHO_RTX(105),
    BANCHO_MATCH_ABORT(106),
    BANCHO_SWITCH_TOURNAMENT_SERVER(107),

    // Packets that are unused today, but used in legacy clients
    OSU_MATCH_CHANGE_BEATMAP(65534),
    BANCHO_HANDLE_IRC_JOIN(65535);

    private final int id;

    public static Packets fromId(int id) {
        for (Packets type : values()) {
            if (type.id == id) {
                return type;
            }
        }
        throw new IllegalArgumentException("Unknown packet id: " + id);
    }
}
